### ISSUE TITLE
Prometheus config is bad 

### ISSUE THREAD

**Issue by fork04** [nefilim/pinger#2]
prometheus    | level=info ts=2019-11-20T21:44:25.932Z caller=main.go:672 fs_type=EXT4_SUPER_MAGIC
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:673 msg="TSDB started"
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:743 msg="Loading configuration file" filename=prometheus.yml
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:526 msg="Stopping scrape discovery manager..."
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:540 msg="Stopping notify discovery manager..."
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:562 msg="Stopping scrape manager..."
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:522 msg="Scrape discovery manager stopped"
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=manager.go:814 component="rule manager" msg="Stopping rule manager..."
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=manager.go:820 component="rule manager" msg="Rule manager stopped"
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:536 msg="Notify discovery manager stopped"
prometheus    | level=info ts=2019-11-20T21:44:25.933Z caller=main.go:556 msg="Scrape manager stopped"
prometheus    | level=info ts=2019-11-20T21:44:25.939Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
prometheus    | level=info ts=2019-11-20T21:44:25.939Z caller=main.go:727 msg="Notifier manager stopped"
prometheus    | level=error ts=2019-11-20T21:44:25.940Z caller=main.go:736 err="error loading config from \"prometheus.yml\": couldn't load configuration (--config.file=\"prometheus.yml\"): open prometheus.yml: no such file or directory"

**Comment by fork04** [comment]
Should be:

command:
      # prometheus retention period
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=7d'
      - '--storage.tsdb.path=/prometheus'

**Comment by nefilim** [comment]
Thanks for the report & fix, looks like Prometheus changed their container workdir in recent versions. 

https://github.com/nefilim/pinger/pull/3
